<?php if (! $this->compact): ?>
<div class="controls">
    <?= $this->tabs ?>
</div>
<?php endif ?>
<div class="content">
    <div class="tlv-overview-tiles">
    <?php
    /** @var array $views **/
    foreach ($views as $name => $view):
    /** @var \Icinga\Module\Toplevelview\ViewConfig $view */
    ?>
    <?= $this->qlink(
            $view->getMeta('name'),
            'toplevelview/show',
            array('name' => $name),
            array('class' => 'tlv-overview-tile')
    ) ?>
    <?php endforeach; ?>
    </div>
</div>
