<?php
/** @var \Icinga\Web\View $this */
/** @var \Icinga\Module\Toplevelview\ViewConfig $view */
if (! $this->compact):
?>
<div class="controls">
    <?= $this->tabs ?>
</div>
<?php endif ?>
<div class="content tlv-content">
    <div class="tlv-header">
        <div class="last-refresh">
            <?= $this->translate('Last update') ?>
            <?= $this->timeAgo($view->getTree()->getFetchTime()) ?>
        </div>
        <h1><?= $view->getMeta('name') ?></h1>
        <?= $this->partial('show/actions.phtml', $this) ?>
    </div>
    <div class="tlv-view-tiles">
        <?php foreach ($view->getTree()->getChildren() as $topTile): ?>
            <?= $this->tiles($topTile) ?>
        <?php endforeach; ?>
    </div>
</div>
