<?php
/** @var \Icinga\Module\Toplevelview\ViewConfig $view */
/** @var \Icinga\Module\Toplevelview\Tree\TLVTreeNode $node */

if (! $this->compact):
?>
<div class="controls">
    <?= $this->tabs ?>
</div>
<?php endif ?>
<div class="content tlv-view-tree">
    <div class="tlv-header">
        <div class="last-refresh">
            <?= $this->translate('Last update') ?>
            <?= $this->timeAgo($view->getTree()->getFetchTime()) ?>
        </div>
        <h1><?= $view->getMeta('name') ?></h1>
        <?= $this->partial('show/actions.phtml', $this) ?>
    </div>
    <?= $this->breadcrumb($node->getBreadCrumb(), $view->getName()) ?>
    <?= $this->tree($node) ?>
</div>
