<?php
use Icinga\Module\Toplevelview\Util\Str;

/** @var \Icinga\Module\Toplevelview\ViewConfig $view */
/** @var \Icinga\Module\Toplevelview\Tree\TLVTreeNode $node */

$tree = $view->getTree();

if (! $this->compact):
?>
<div class="controls separated">
    <?= $this->tabs ?>
    <?= $this->partial('show/actions.phtml', $this) ?>
</div>
<?php endif ?>
<div class="content tlv-view-tree">
    <div class="tlv-header">
        <h1><?= $view->getMeta('name') ?></h1>
        <div class="last-refresh"><?= $this->timeAgo($tree->getFetchTime()) ?></div>
        <?= $this->badges($tree->getStatus(), false, true) ?>
    </div>
    <?= $this->breadcrumb($node->getBreadCrumb(), $view->getName()) ?>
    <?= $this->tree($node) ?>
</div>
