name: PHP Tests

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

jobs:
  lint:
    name: Static analysis for php ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1', '8.2']
        os: ['ubuntu-latest']

    steps:
      - name: Checkout code base
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpcs

      - name: Setup dependencies
        run: composer require -n --no-progress overtrue/phplint

      - name: PHP Lint
        if: success() || matrix.allow_failure
        run: ./vendor/bin/phplint -n --exclude={^vendor/.*} -- .

      - name: PHP CodeSniffer
        if: success() || matrix.allow_failure
        run: phpcs -wps --colors

      - name: Setup Libraries
        run: |
          mkdir -p _libraries
          git clone --depth 1 -b snapshot/nightly https://github.com/Icinga/icinga-php-library.git _libraries/ipl
          git clone --depth 1 -b snapshot/nightly https://github.com/Icinga/icinga-php-thirdparty.git _libraries/vendor
          git clone --depth 1 https://github.com/Icinga/icingaweb2.git _icingaweb2
          git clone --depth 1 https://github.com/Icinga/icingadb-web.git _icingaweb2/modules/icingadb
          ln -s `pwd` _icingaweb2/modules/toplevelview

      - name: PHPUnit
        env:
          ICINGAWEB_LIBDIR:  _libraries/
        run: phpunit --verbose
